-- Create Term table
create table public."Term" (
  id bigint generated by default as identity primary key,
  name text not null unique,
  aliases text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Translation table
create table public."Translation" (
  id bigint generated by default as identity primary key,
  term_id bigint references public."Term" (id) on delete cascade not null,
  text text not null,
  is_preferred boolean default false,
  usage text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public."Term" enable row level security;
alter table public."Translation" enable row level security;

-- Create Policy: Allow public read access
create policy "Allow public read access on Term"
  on public."Term" for select
  using (true);

create policy "Allow public read access on Translation"
  on public."Translation" for select
  using (true);

-- Create Policy: Allow authenticated insert/update (Optional for now, allowing anon for dev if needed)
-- For development simplicity, allowing anon insert for now (User can restrict later)
create policy "Allow anon insert on Term"
  on public."Term" for insert
  with check (true);

create policy "Allow anon insert on Translation"
  on public."Translation" for insert
  with check (true);
